# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3c3b05e789bc1d4d987558a41cefc8a4d4a34dde37ebd0a4fa7ee5258154ac4b9e6d0f4db62ae811c3269a7ff9421c110ca830e7b910675b96a91bef5b55624

test:
  secret_key_base: 7d87eaf07285eaf6a3f086401438b016573562719d089abef9ee52ebb9bda9ec363080f3c14aebc1bf0aad635491d8934038c78a67d5d738cc93c8c8f9ea36bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
